language: python

env:
  global:
  - USER="suphero"
  - EMAIL="deploy@travis-ci.org"
  - DEPLOYMENT_USER="traviscibot"
  - REPO="harunsokullucom"
  - FILES="./public/*"
  - GH_REPO="github.com/${USER}/${REPO}.git"

after_success:
  - MESSAGE=$(git log -1 --pretty=%B)
  - git clone git://${GH_REPO}
  - cd ${REPO}
  - rm -rf `ls | grep -v 'md$' | grep -v '.git' | grep -v 'CNAME'`
  - cp -f -r ../${FILES} ./
  - ls
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${DEPLOYMENT_USER}
  - git add .
  - git commit -m "${MESSAGE}"
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" master

install:
    - sudo snap install hugo

script:
    - hugo -s ./